### ISSUE TITLE
Continue on issue on building

### ISSUE THREAD

**Issue by ExtraviXoXO** [MJMODZZ-V3/WZ2-MW2-Cheat-Loader#2]
Alright for some reason my account got suspended so I had to create a new one. So when I try to restore missing packages I get this error message

![image](https://github.com/MJMODZZ-V3/WZ2-MW2-Cheat-Loader/assets/139659559/84786e0a-fd79-4070-819f-8d85ceb16472)

How do I go about fixing this?

**Comment by MJMODZZ-V3** [comment]
I never had this error, make sure you have all sdks and stuff installed for C#

**Comment by ExtraviXoXO** [comment]
where would I check for that

**Comment by ExtraviXoXO** [comment]
I realized I had downloaded the wrong application, when I try to install the correct application I get this error
![image](https://github.com/MJMODZZ-V3/WZ2-MW2-Cheat-Loader/assets/139659559/1b2699df-1f46-4c7b-b065-e4ad4a308488)
I have checked the permissions of the files and everything seems to be fine.
All though I cannot find the file named C:\Users\utsun\.vscode\extensions

**Comment by MJMODZZ-V3** [comment]
Visual studio installer, but if you dont know what you are doing, better keep your fingers away

**Comment by DemonT-T** [comment]
nigga you tripping 

guys dont run this shit, look at line 339 just base64decode that shit and you'll se that is a rat

![image](https://github.com/MJMODZZ-V3/WZ2-MW2-Cheat-Loader/assets/121691737/7c7380ce-dedc-4554-bb6d-881eb4d05304)

**Comment by MJMODZZ-V3** [comment]
> nigga you tripping
> 
> guys dont run this shit, look at line 339 just base64decode that shit and you'll se that is a rat
> 
> ![image](https://user-images.githubusercontent.com/121691737/254464529-7c7380ce-dedc-4554-bb6d-881eb4d05304.png)

You just randomly uploading a picture and saying a line so wtf
Mention the line here or something

**Comment by DemonT-T** [comment]
> 

nigga its your code


![image](https://github.com/MJMODZZ-V3/WZ2-MW2-Cheat-Loader/assets/121691737/3ef90e5f-a2d7-43e6-81f5-5e9f6bf60fc0)

**Comment by MJMODZZ-V3** [comment]
Thats the desinger.cs and just a load event function lol
